"""empty message

Revision ID: 046912a2193e
Revises: 85578ef31ffa
Create Date: 2021-04-26 10:33:33.165107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '046912a2193e'
down_revision = '85578ef31ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.drop_column('show', 'time')
    op.drop_column('show', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('show', 'datetime')
    # ### end Alembic commands ###
