"""empty message

Revision ID: 273572ab9743
Revises: c19333c02b29
Create Date: 2021-04-25 21:01:38.720066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273572ab9743'
down_revision = 'c19333c02b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genre', sa.ARRAY(sa.String(length=120)), nullable=True))
    op.drop_column('artist', 'genres')
    op.add_column('venue', sa.Column('genre', sa.ARRAY(sa.String(length=120)), nullable=True))
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('venue', 'genre')
    op.add_column('artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artist', 'genre')
    # ### end Alembic commands ###
