"""empty message

Revision ID: 6d4ed46a3d88
Revises: 4b0e81fdcf89
Create Date: 2021-04-25 19:53:02.991624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4ed46a3d88'
down_revision = '4b0e81fdcf89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.drop_column('artist', 'venue_quote')
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.drop_column('venue', 'talent_quote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('talent_quote', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('venue', 'seeking_description')
    op.add_column('artist', sa.Column('venue_quote', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###
