"""empty message

Revision ID: 85578ef31ffa
Revises: 273572ab9743
Create Date: 2021-04-26 08:23:17.404487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85578ef31ffa'
down_revision = '273572ab9743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=True))
    op.drop_column('artist', 'genre')
    op.add_column('venue', sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=True))
    op.drop_column('venue', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genre', postgresql.ARRAY(sa.VARCHAR(length=120)), autoincrement=False, nullable=True))
    op.drop_column('venue', 'genres')
    op.add_column('artist', sa.Column('genre', postgresql.ARRAY(sa.VARCHAR(length=120)), autoincrement=False, nullable=True))
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###
